// Generated by gencpp from file robot_navigation/SimLog.msg
// DO NOT EDIT!


#ifndef ROBOT_NAVIGATION_MESSAGE_SIMLOG_H
#define ROBOT_NAVIGATION_MESSAGE_SIMLOG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace robot_navigation
{
template <class ContainerAllocator>
struct SimLog_
{
  typedef SimLog_<ContainerAllocator> Type;

  SimLog_()
    : header()
    , robot_pos()
    , goal()
    , dist_from_goal(0.0)
    , collision()
    , iteration(0)
    , event()  {
    }
  SimLog_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_pos(_alloc)
    , goal(_alloc)
    , dist_from_goal(0.0)
    , collision(_alloc)
    , iteration(0)
    , event(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _robot_pos_type;
  _robot_pos_type robot_pos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef double _dist_from_goal_type;
  _dist_from_goal_type dist_from_goal;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _collision_type;
  _collision_type collision;

   typedef uint8_t _iteration_type;
  _iteration_type iteration;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type;
  _event_type event;





  typedef boost::shared_ptr< ::robot_navigation::SimLog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_navigation::SimLog_<ContainerAllocator> const> ConstPtr;

}; // struct SimLog_

typedef ::robot_navigation::SimLog_<std::allocator<void> > SimLog;

typedef boost::shared_ptr< ::robot_navigation::SimLog > SimLogPtr;
typedef boost::shared_ptr< ::robot_navigation::SimLog const> SimLogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_navigation::SimLog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_navigation::SimLog_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_navigation::SimLog_<ContainerAllocator1> & lhs, const ::robot_navigation::SimLog_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_pos == rhs.robot_pos &&
    lhs.goal == rhs.goal &&
    lhs.dist_from_goal == rhs.dist_from_goal &&
    lhs.collision == rhs.collision &&
    lhs.iteration == rhs.iteration &&
    lhs.event == rhs.event;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_navigation::SimLog_<ContainerAllocator1> & lhs, const ::robot_navigation::SimLog_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::SimLog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_navigation::SimLog_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::SimLog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_navigation::SimLog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::SimLog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_navigation::SimLog_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_navigation::SimLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc387dc22a2d950d15b2be5ad31d16db";
  }

  static const char* value(const ::robot_navigation::SimLog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc387dc22a2d950dULL;
  static const uint64_t static_value2 = 0x15b2be5ad31d16dbULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_navigation::SimLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_navigation/SimLog";
  }

  static const char* value(const ::robot_navigation::SimLog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_navigation::SimLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Pose2D robot_pos\n"
"geometry_msgs/Point goal\n"
"float64 dist_from_goal\n"
"geometry_msgs/Point collision\n"
"uint8 iteration\n"
"string event\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robot_navigation::SimLog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_navigation::SimLog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_pos);
      stream.next(m.goal);
      stream.next(m.dist_from_goal);
      stream.next(m.collision);
      stream.next(m.iteration);
      stream.next(m.event);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimLog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_navigation::SimLog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_navigation::SimLog_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_pos);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "dist_from_goal: ";
    Printer<double>::stream(s, indent + "  ", v.dist_from_goal);
    s << indent << "collision: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.collision);
    s << indent << "iteration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.iteration);
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_NAVIGATION_MESSAGE_SIMLOG_H
