#! /usr/bin/env python

import rospy
from goal_checker_server.node_server import NodeAliveServer

if __name__ == '__main__':
    try:
        rospy.init_node('check_node_is_alive_server')
        server = NodeAliveServer()

        # Prints to see if everything is working or not 
        print("================================= Starting Node Server ==========================================")
        server.loop()
    except rospy.ROSInterruptException:
        pass
