#!/usr/bin/env python

from optparse import OptionParser
import rospy
from std_msgs.msg import String
from goal_checker_server.utilities import get_node_names


if __name__ == '__main__':
    print("--------------------------------------- ROSPY INIT -----------------------------------")
    rospy.init_node('check_node_is_alive')

    parser = OptionParser(usage="usage: \t check_node_is_alive [roslaunch_file]")

    options, args = parser.parse_args()
    if not args:
        parser.error('Please Specify a roslaunch_file')

    pub = rospy.Publisher('check_alive_nodes', String)

    for node in get_node_names([args[0]]):
        if node[-4:] != "_tmp":
            pub.publish(node)
            rospy.loginfo("Adding '%s' to check_node_is_alive_server" % node)
